// This file was auto-generated by sync-env.js
export const environment = {
  production: false,
  apiUrl: 'https://api.zeven.kelompok27.com/api',
  storageUrl: 'https://api.zeven.kelompok27.com/storage'
};
